### ISSUE TITLE
error LNK2001:  Unresolved external symbol __r_wnd_messageloop，__r_wnd_adjustworkingarea

### ISSUE THREAD

**Issue by xiaojunhuan** [henrypp/routine#10]
1>[WARNING!] Compile-time warning: IDS_UPDATE_AUTOINSTALL ("D:\\projects\\cpluscplusprojects\\project08\\memreduct-v.3.4\\src\\rapp.c":3027)
1>D:\projects\cpluscplusprojects\project08\memreduct-v.3.4\src\main.c(10,9): warning C4616: #pragma warning: 警告编号“2220”不是有效的编译器警告
1>D:\projects\cpluscplusprojects\project08\memreduct-v.3.4\src\main.c(1963,33): warning C4013: “_r_wnd_adjustworkingarea”未定义；假设外部返回 int
1>D:\projects\cpluscplusprojects\project08\memreduct-v.3.4\src\main.c(2620,28): warning C4013: “_r_wnd_messageloop”未定义；假设外部返回 int
1>main.obj : error LNK2001: 无法解析的外部符号 __r_wnd_messageloop@8
1>main.obj : error LNK2001: 无法解析的外部符号 __r_wnd_adjustworkingarea@8
1>D:\projects\cpluscplusprojects\project08\memreduct-v.3.4\bin\32\memreduct.exe : fatal error LNK1120: 2 个无法解析的外部命令

**Comment by WMdoit** [comment]
你也在利用这个写simplewall相关的吗？我一直编译失败
